//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Name="administrator.contact.1.0.0", Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", ConfigurationName="ServiceReference1.administratorcontact100")]
    public interface administratorcontact100
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="readList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.readListResponse> readListAsync(ServiceReference1.readListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="readItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.readItemResponse> readItemAsync(ServiceReference1.readItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.createResponse> createAsync(ServiceReference1.createRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.updateResponse> updateAsync(ServiceReference1.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.deleteResponse> deleteAsync(ServiceReference1.deleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_featured", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.task_featuredResponse> task_featuredAsync(ServiceReference1.task_featuredRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_unfeatured", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.task_unfeaturedResponse> task_unfeaturedAsync(ServiceReference1.task_unfeaturedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_publish", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.task_publishResponse> task_publishAsync(ServiceReference1.task_publishRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_unpublish", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.task_unpublishResponse> task_unpublishAsync(ServiceReference1.task_unpublishRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_checkin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.task_checkinResponse> task_checkinAsync(ServiceReference1.task_checkinRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_checkout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.task_checkoutResponse> task_checkoutAsync(ServiceReference1.task_checkoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.task_saveResponse> task_saveAsync(ServiceReference1.task_saveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_apply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.task_applyResponse> task_applyAsync(ServiceReference1.task_applyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="task_delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.task_deleteResponse> task_deleteAsync(ServiceReference1.task_deleteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl")]
    public partial class readList_filters
    {
        
        private int publishedField;
        
        private bool publishedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int published
        {
            get
            {
                return this.publishedField;
            }
            set
            {
                this.publishedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool publishedSpecified
        {
            get
            {
                return this.publishedFieldSpecified;
            }
            set
            {
                this.publishedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl")]
    public partial class readItemResponse_item
    {
        
        private int idField;
        
        private string nameField;
        
        private string aliasField;
        
        private string con_positionField;
        
        private string addressField;
        
        private string suburbField;
        
        private string stateField;
        
        private string countryField;
        
        private string postcodeField;
        
        private string telephoneField;
        
        private string faxField;
        
        private string miscField;
        
        private string imageField;
        
        private string email_toField;
        
        private int default_conField;
        
        private int publishedField;
        
        private int checked_outField;
        
        private System.DateTime checked_out_timeField;
        
        private int orderingField;
        
        private string paramsField;
        
        private int user_idField;
        
        private int catidField;
        
        private int accessField;
        
        private string mobileField;
        
        private string webpageField;
        
        private string sortname1Field;
        
        private string sortname2Field;
        
        private string sortname3Field;
        
        private string languageField;
        
        private System.DateTime createdField;
        
        private int created_byField;
        
        private System.DateTime modifiedField;
        
        private int modified_byField;
        
        private string metakeyField;
        
        private string metadescField;
        
        private string metadataField;
        
        private int featuredField;
        
        private System.DateTime publish_upField;
        
        private System.DateTime publish_downField;
        
        private string versionField;
        
        private int hitsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string con_position
        {
            get
            {
                return this.con_positionField;
            }
            set
            {
                this.con_positionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string suburb
        {
            get
            {
                return this.suburbField;
            }
            set
            {
                this.suburbField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string postcode
        {
            get
            {
                return this.postcodeField;
            }
            set
            {
                this.postcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telephone
        {
            get
            {
                return this.telephoneField;
            }
            set
            {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string misc
        {
            get
            {
                return this.miscField;
            }
            set
            {
                this.miscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string image
        {
            get
            {
                return this.imageField;
            }
            set
            {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string email_to
        {
            get
            {
                return this.email_toField;
            }
            set
            {
                this.email_toField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public int default_con
        {
            get
            {
                return this.default_conField;
            }
            set
            {
                this.default_conField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public int published
        {
            get
            {
                return this.publishedField;
            }
            set
            {
                this.publishedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public int checked_out
        {
            get
            {
                return this.checked_outField;
            }
            set
            {
                this.checked_outField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public System.DateTime checked_out_time
        {
            get
            {
                return this.checked_out_timeField;
            }
            set
            {
                this.checked_out_timeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public int ordering
        {
            get
            {
                return this.orderingField;
            }
            set
            {
                this.orderingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string @params
        {
            get
            {
                return this.paramsField;
            }
            set
            {
                this.paramsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int user_id
        {
            get
            {
                return this.user_idField;
            }
            set
            {
                this.user_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public int catid
        {
            get
            {
                return this.catidField;
            }
            set
            {
                this.catidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public int access
        {
            get
            {
                return this.accessField;
            }
            set
            {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string mobile
        {
            get
            {
                return this.mobileField;
            }
            set
            {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string webpage
        {
            get
            {
                return this.webpageField;
            }
            set
            {
                this.webpageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string sortname1
        {
            get
            {
                return this.sortname1Field;
            }
            set
            {
                this.sortname1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string sortname2
        {
            get
            {
                return this.sortname2Field;
            }
            set
            {
                this.sortname2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string sortname3
        {
            get
            {
                return this.sortname3Field;
            }
            set
            {
                this.sortname3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=29)]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=30)]
        public int created_by
        {
            get
            {
                return this.created_byField;
            }
            set
            {
                this.created_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=31)]
        public System.DateTime modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=32)]
        public int modified_by
        {
            get
            {
                return this.modified_byField;
            }
            set
            {
                this.modified_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=33)]
        public string metakey
        {
            get
            {
                return this.metakeyField;
            }
            set
            {
                this.metakeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=34)]
        public string metadesc
        {
            get
            {
                return this.metadescField;
            }
            set
            {
                this.metadescField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=35)]
        public string metadata
        {
            get
            {
                return this.metadataField;
            }
            set
            {
                this.metadataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=36)]
        public int featured
        {
            get
            {
                return this.featuredField;
            }
            set
            {
                this.featuredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=37)]
        public System.DateTime publish_up
        {
            get
            {
                return this.publish_upField;
            }
            set
            {
                this.publish_upField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=38)]
        public System.DateTime publish_down
        {
            get
            {
                return this.publish_downField;
            }
            set
            {
                this.publish_downField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=39)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=40)]
        public int hits
        {
            get
            {
                return this.hitsField;
            }
            set
            {
                this.hitsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl")]
    public partial class readListResponse_list_item
    {
        
        private int idField;
        
        private int accessField;
        
        private int featuredField;
        
        private string languageField;
        
        private string nameField;
        
        private int orderingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int access
        {
            get
            {
                return this.accessField;
            }
            set
            {
                this.accessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int featured
        {
            get
            {
                return this.featuredField;
            }
            set
            {
                this.featuredField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int ordering
        {
            get
            {
                return this.orderingField;
            }
            set
            {
                this.orderingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readList", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class readListRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limitStart;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int limit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filterSearch;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.readList_filters filters;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ordering;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderingDirection;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        public readListRequest()
        {
        }
        
        public readListRequest(int limitStart, int limit, string filterSearch, ServiceReference1.readList_filters filters, string ordering, string orderingDirection, string language)
        {
            this.limitStart = limitStart;
            this.limit = limit;
            this.filterSearch = filterSearch;
            this.filters = filters;
            this.ordering = ordering;
            this.orderingDirection = orderingDirection;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readListResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class readListResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ServiceReference1.readListResponse_list_item[] list;
        
        public readListResponse()
        {
        }
        
        public readListResponse(ServiceReference1.readListResponse_list_item[] list)
        {
            this.list = list;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readItem", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class readItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        public readItemRequest()
        {
        }
        
        public readItemRequest(int id, string language)
        {
            this.id = id;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readItemResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class readItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceReference1.readItemResponse_item item;
        
        public readItemResponse()
        {
        }
        
        public readItemResponse(ServiceReference1.readItemResponse_item item)
        {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class createRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int catid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int published;
        
        public createRequest()
        {
        }
        
        public createRequest(string name, int catid, string language, int published)
        {
            this.name = name;
            this.catid = catid;
            this.language = language;
            this.published = published;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class createResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public createResponse()
        {
        }
        
        public createResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="update", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class updateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int catid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int published;
        
        public updateRequest()
        {
        }
        
        public updateRequest(int id, string name, int catid, string language, int published)
        {
            this.id = id;
            this.name = name;
            this.catid = catid;
            this.language = language;
            this.published = published;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class updateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public updateResponse()
        {
        }
        
        public updateResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class deleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public deleteRequest()
        {
        }
        
        public deleteRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class deleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public deleteResponse()
        {
        }
        
        public deleteResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_featured", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_featuredRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_featuredRequest()
        {
        }
        
        public task_featuredRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_featuredResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_featuredResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_featuredResponse()
        {
        }
        
        public task_featuredResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_unfeatured", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_unfeaturedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_unfeaturedRequest()
        {
        }
        
        public task_unfeaturedRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_unfeaturedResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_unfeaturedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_unfeaturedResponse()
        {
        }
        
        public task_unfeaturedResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_publish", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_publishRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_publishRequest()
        {
        }
        
        public task_publishRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_publishResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_publishResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_publishResponse()
        {
        }
        
        public task_publishResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_unpublish", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_unpublishRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_unpublishRequest()
        {
        }
        
        public task_unpublishRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_unpublishResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_unpublishResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_unpublishResponse()
        {
        }
        
        public task_unpublishResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_checkin", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_checkinRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_checkinRequest()
        {
        }
        
        public task_checkinRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_checkinResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_checkinResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_checkinResponse()
        {
        }
        
        public task_checkinResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_checkout", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_checkoutRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int id;
        
        public task_checkoutRequest()
        {
        }
        
        public task_checkoutRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_checkoutResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_checkoutResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_checkoutResponse()
        {
        }
        
        public task_checkoutResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_save", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_saveRequest
    {
        
        public task_saveRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_saveResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_saveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_saveResponse()
        {
        }
        
        public task_saveResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_apply", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_applyRequest
    {
        
        public task_applyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_applyResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_applyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_applyResponse()
        {
        }
        
        public task_applyResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_delete", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_deleteRequest
    {
        
        public task_deleteRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="task_deleteResponse", WrapperNamespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
        ".contact.1.0.0.wsdl", IsWrapped=true)]
    public partial class task_deleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://api.softwareavanzado.world/media/redcore/webservices/joomla/administrator" +
            ".contact.1.0.0.wsdl", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool result;
        
        public task_deleteResponse()
        {
        }
        
        public task_deleteResponse(bool result)
        {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface administratorcontact100Channel : ServiceReference1.administratorcontact100, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class administratorcontact100Client : System.ServiceModel.ClientBase<ServiceReference1.administratorcontact100>, ServiceReference1.administratorcontact100
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public administratorcontact100Client() : 
                base(administratorcontact100Client.GetDefaultBinding(), administratorcontact100Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.administrator_contact_1_0_0_Soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public administratorcontact100Client(EndpointConfiguration endpointConfiguration) : 
                base(administratorcontact100Client.GetBindingForEndpoint(endpointConfiguration), administratorcontact100Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public administratorcontact100Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(administratorcontact100Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public administratorcontact100Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(administratorcontact100Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public administratorcontact100Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.readListResponse> ServiceReference1.administratorcontact100.readListAsync(ServiceReference1.readListRequest request)
        {
            return base.Channel.readListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.readListResponse> readListAsync(int limitStart, int limit, string filterSearch, ServiceReference1.readList_filters filters, string ordering, string orderingDirection, string language)
        {
            ServiceReference1.readListRequest inValue = new ServiceReference1.readListRequest();
            inValue.limitStart = limitStart;
            inValue.limit = limit;
            inValue.filterSearch = filterSearch;
            inValue.filters = filters;
            inValue.ordering = ordering;
            inValue.orderingDirection = orderingDirection;
            inValue.language = language;
            return ((ServiceReference1.administratorcontact100)(this)).readListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.readItemResponse> ServiceReference1.administratorcontact100.readItemAsync(ServiceReference1.readItemRequest request)
        {
            return base.Channel.readItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.readItemResponse> readItemAsync(int id, string language)
        {
            ServiceReference1.readItemRequest inValue = new ServiceReference1.readItemRequest();
            inValue.id = id;
            inValue.language = language;
            return ((ServiceReference1.administratorcontact100)(this)).readItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.createResponse> ServiceReference1.administratorcontact100.createAsync(ServiceReference1.createRequest request)
        {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.createResponse> createAsync(string name, int catid, string language, int published)
        {
            ServiceReference1.createRequest inValue = new ServiceReference1.createRequest();
            inValue.name = name;
            inValue.catid = catid;
            inValue.language = language;
            inValue.published = published;
            return ((ServiceReference1.administratorcontact100)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.updateResponse> ServiceReference1.administratorcontact100.updateAsync(ServiceReference1.updateRequest request)
        {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.updateResponse> updateAsync(int id, string name, int catid, string language, int published)
        {
            ServiceReference1.updateRequest inValue = new ServiceReference1.updateRequest();
            inValue.id = id;
            inValue.name = name;
            inValue.catid = catid;
            inValue.language = language;
            inValue.published = published;
            return ((ServiceReference1.administratorcontact100)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.deleteResponse> ServiceReference1.administratorcontact100.deleteAsync(ServiceReference1.deleteRequest request)
        {
            return base.Channel.deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.deleteResponse> deleteAsync(int id)
        {
            ServiceReference1.deleteRequest inValue = new ServiceReference1.deleteRequest();
            inValue.id = id;
            return ((ServiceReference1.administratorcontact100)(this)).deleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.task_featuredResponse> ServiceReference1.administratorcontact100.task_featuredAsync(ServiceReference1.task_featuredRequest request)
        {
            return base.Channel.task_featuredAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.task_featuredResponse> task_featuredAsync(int id)
        {
            ServiceReference1.task_featuredRequest inValue = new ServiceReference1.task_featuredRequest();
            inValue.id = id;
            return ((ServiceReference1.administratorcontact100)(this)).task_featuredAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.task_unfeaturedResponse> ServiceReference1.administratorcontact100.task_unfeaturedAsync(ServiceReference1.task_unfeaturedRequest request)
        {
            return base.Channel.task_unfeaturedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.task_unfeaturedResponse> task_unfeaturedAsync(int id)
        {
            ServiceReference1.task_unfeaturedRequest inValue = new ServiceReference1.task_unfeaturedRequest();
            inValue.id = id;
            return ((ServiceReference1.administratorcontact100)(this)).task_unfeaturedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.task_publishResponse> ServiceReference1.administratorcontact100.task_publishAsync(ServiceReference1.task_publishRequest request)
        {
            return base.Channel.task_publishAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.task_publishResponse> task_publishAsync(int id)
        {
            ServiceReference1.task_publishRequest inValue = new ServiceReference1.task_publishRequest();
            inValue.id = id;
            return ((ServiceReference1.administratorcontact100)(this)).task_publishAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.task_unpublishResponse> ServiceReference1.administratorcontact100.task_unpublishAsync(ServiceReference1.task_unpublishRequest request)
        {
            return base.Channel.task_unpublishAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.task_unpublishResponse> task_unpublishAsync(int id)
        {
            ServiceReference1.task_unpublishRequest inValue = new ServiceReference1.task_unpublishRequest();
            inValue.id = id;
            return ((ServiceReference1.administratorcontact100)(this)).task_unpublishAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.task_checkinResponse> ServiceReference1.administratorcontact100.task_checkinAsync(ServiceReference1.task_checkinRequest request)
        {
            return base.Channel.task_checkinAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.task_checkinResponse> task_checkinAsync(int id)
        {
            ServiceReference1.task_checkinRequest inValue = new ServiceReference1.task_checkinRequest();
            inValue.id = id;
            return ((ServiceReference1.administratorcontact100)(this)).task_checkinAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.task_checkoutResponse> ServiceReference1.administratorcontact100.task_checkoutAsync(ServiceReference1.task_checkoutRequest request)
        {
            return base.Channel.task_checkoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.task_checkoutResponse> task_checkoutAsync(int id)
        {
            ServiceReference1.task_checkoutRequest inValue = new ServiceReference1.task_checkoutRequest();
            inValue.id = id;
            return ((ServiceReference1.administratorcontact100)(this)).task_checkoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.task_saveResponse> ServiceReference1.administratorcontact100.task_saveAsync(ServiceReference1.task_saveRequest request)
        {
            return base.Channel.task_saveAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.task_saveResponse> task_saveAsync()
        {
            ServiceReference1.task_saveRequest inValue = new ServiceReference1.task_saveRequest();
            return ((ServiceReference1.administratorcontact100)(this)).task_saveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.task_applyResponse> ServiceReference1.administratorcontact100.task_applyAsync(ServiceReference1.task_applyRequest request)
        {
            return base.Channel.task_applyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.task_applyResponse> task_applyAsync()
        {
            ServiceReference1.task_applyRequest inValue = new ServiceReference1.task_applyRequest();
            return ((ServiceReference1.administratorcontact100)(this)).task_applyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.task_deleteResponse> ServiceReference1.administratorcontact100.task_deleteAsync(ServiceReference1.task_deleteRequest request)
        {
            return base.Channel.task_deleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.task_deleteResponse> task_deleteAsync()
        {
            ServiceReference1.task_deleteRequest inValue = new ServiceReference1.task_deleteRequest();
            return ((ServiceReference1.administratorcontact100)(this)).task_deleteAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.administrator_contact_1_0_0_Soap))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.administrator_contact_1_0_0_Soap))
            {
                return new System.ServiceModel.EndpointAddress("https://api.softwareavanzado.world/administrator/index.php?webserviceClient=admin" +
                        "istrator&webserviceVersion=1.0.0&option=contact&api=soap");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return administratorcontact100Client.GetBindingForEndpoint(EndpointConfiguration.administrator_contact_1_0_0_Soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return administratorcontact100Client.GetEndpointAddress(EndpointConfiguration.administrator_contact_1_0_0_Soap);
        }
        
        public enum EndpointConfiguration
        {
            
            administrator_contact_1_0_0_Soap,
        }
    }
}
